### ISSUE TITLE
Trying to compile for WRT160N V2 and pkg-config is giving me this error.

### ISSUE THREAD

**Issue by awtivy** [leitec/openwrt-leitec#1]
libtool: link: ( cd ".libs" && rm -f "libglib-2.0.la" && ln -s "../libglib-2.0.la" "libglib-2.0.la" )
echo   > glib-public-headers.txt.tmp && mv glib-public-headers.txt.tmp glib-public-headers.txt
Making all in .
gcc -DHAVE_CONFIG_H -I.  -DPKG_CONFIG_PC_PATH="\"/Volumes/OpenWRT/staging_dir/host/lib/pkgconfig:/Volumes/OpenWRT/staging_dir/host/share/pkgconfig\"" -DPKG_CONFIG_SYSTEM_INCLUDE_PATH="\"/usr/include\"" -DPKG_CONFIG_SYSTEM_LIBRARY_PATH="\"/usr/lib:/lib\"" -I/Volumes/OpenWRT/staging_dir/host/include   -I./glib -I./glib/glib -I./glib/glib -O2 -I/Volumes/OpenWRT/staging_dir/host/include -MT pkg.o -MD -MP -MF .deps/pkg.Tpo -c -o pkg.o pkg.c
mv -f .deps/pkg.Tpo .deps/pkg.Po
gcc -DHAVE_CONFIG_H -I.  -DPKG_CONFIG_PC_PATH="\"/Volumes/OpenWRT/staging_dir/host/lib/pkgconfig:/Volumes/OpenWRT/staging_dir/host/share/pkgconfig\"" -DPKG_CONFIG_SYSTEM_INCLUDE_PATH="\"/usr/include\"" -DPKG_CONFIG_SYSTEM_LIBRARY_PATH="\"/usr/lib:/lib\"" -I/Volumes/OpenWRT/staging_dir/host/include   -I./glib -I./glib/glib -I./glib/glib -O2 -I/Volumes/OpenWRT/staging_dir/host/include -MT parse.o -MD -MP -MF .deps/parse.Tpo -c -o parse.o parse.c
mv -f .deps/parse.Tpo .deps/parse.Po
gcc -DHAVE_CONFIG_H -I.  -DPKG_CONFIG_PC_PATH="\"/Volumes/OpenWRT/staging_dir/host/lib/pkgconfig:/Volumes/OpenWRT/staging_dir/host/share/pkgconfig\"" -DPKG_CONFIG_SYSTEM_INCLUDE_PATH="\"/usr/include\"" -DPKG_CONFIG_SYSTEM_LIBRARY_PATH="\"/usr/lib:/lib\"" -I/Volumes/OpenWRT/staging_dir/host/include   -I./glib -I./glib/glib -I./glib/glib -O2 -I/Volumes/OpenWRT/staging_dir/host/include -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
/bin/bash ./libtool  --tag=CC   --mode=link gcc   -I./glib -I./glib/glib -I./glib/glib -O2 -I/Volumes/OpenWRT/staging_dir/host/include  -L/Volumes/OpenWRT/staging_dir/host/lib  -o pkg-config pkg.o parse.o main.o ./glib/glib/libglib-2.0.la 
libtool: link: gcc -I./glib -I./glib/glib -I./glib/glib -O2 -I/Volumes/OpenWRT/staging_dir/host/include -o pkg-config pkg.o parse.o main.o  -L/Volumes/OpenWRT/staging_dir/host/lib ./glib/glib/.libs/libglib-2.0.a -liconv -framework Foundation -framework Carbon
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _g_iconv in libglib-2.0.a(gconvert.o)
      _open_converter in libglib-2.0.a(gconvert.o)
      _g_convert_with_iconv in libglib-2.0.a(gconvert.o)
      _g_convert_with_fallback in libglib-2.0.a(gconvert.o)
  "_libiconv_close", referenced from:
      _g_iconv_close in libglib-2.0.a(gconvert.o)
      _iconv_cache_bucket_expire in libglib-2.0.a(gconvert.o)
      _close_converter in libglib-2.0.a(gconvert.o)
  "_libiconv_open", referenced from:
      _try_conversion in libglib-2.0.a(gconvert.o)
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[5]: **\* [pkg-config] Error 1
make[4]: **\* [all-recursive] Error 1
make[3]: **\* [all] Error 2
make[2]: **\* [/Volumes/OpenWRT/build_dir/host/pkg-config-0.28/.built] Error 2
make[2]: Leaving directory `/Volumes/OpenWRT/tools/pkg-config'
make[1]: *** [tools/pkg-config/compile] Error 2
make[1]: Leaving directory`/Volumes/OpenWRT'
make: **\* [tools/compile] Error 2
Alex-Tivys-Mac-Pro:OpenWRT alex$

**Comment by leitec** [comment]
Trying to supply binaries again: http://staticky.com/dl/openwrt-leitec/12.09.1/ramips/rt288x/
