### ISSUE TITLE
Jakko.me's website is down

### ISSUE THREAD

**Issue by yougotborked** [leitec/openwrt-leitec#6]
I am unable to reach https://jakko.me/setting-up-openwrt-on-a-wrt110-and-other-ralink-based-routers/ 

If you have a copy of the text, I would ask that you include it in your repo.

**Comment by leitec** [comment]
Yes, see https://github.com/leitec/openwrt-leitec/issues/5

**Comment by leitec** [comment]
I've added a few links and short instructions to the wiki, similar to what Jakko's site offered.
